-- Main Menu Items

INSERT INTO menu_items (category_id, code) VALUES
(2, 'menu.main.seafood.boil.title'),
(2, 'menu.main.love.platter.title'),
(2, 'menu.main.tapsilog.title'),
(2, 'menu.main.tosilog.title'),
(2, 'menu.main.spamsilog.title'),
(2, 'menu.main.bangsilog.title'),
(2, 'menu.main.cornsilog.title'),
(2, 'menu.main.calamari.title'),
(2, 'menu.main.shanghai.title'),
(2, 'menu.main.siomai.title'),
(2, 'menu.main.tofu.veggies.title'),
(2, 'menu.main.stirfry.veggies.title');


INSERT INTO menu_descriptions (item_id, lang_code, title, description) VALUES
(2,'en','Seafood Boil',''),
(2,'fr','Fruits de Mer Bouillis',''),
(2,'tl','Nilagang Lamang-Dagat',''),
(2,'en','LOVE Platter',''),
(2,'fr','Plat LOVE',''),
(2,'tl','LOVE Platter',''),
(2,'en','Tapsilog','beef, fried egg, garlic fried rice'),
(2,'fr','Tapsilog','bœuf, œuf frit, riz frit à l'\'ail'),
(2,'tl','Tapsilog','karne ng baka, pritong itlog, sinangag'),
(2,'en','Tosilog','pork, fried egg, garlic fried rice'),
(2,'fr','Tosilog','porc, œuf frit, riz frit à l'\'ail'),
(2,'tl','Tosilog','karne ng baboy, pritong itlog, sinangag'),
(2,'en','Spamsilog','spam, fried egg, garlic fried rice'),
(2,'fr','Spamsilog','spam, œuf frit, riz frit à l'\'ail'),
(2,'tl','Spamsilog','spam, pritong itlog, sinangag'),
(2,'en','Bangsilog','fish, fried egg, garlic fried rice'),
(2,'fr','Bangsilog','poisson, œuf frit, riz frit à l'\'ail'),
(2,'tl','Bangsilog','isda, pritong itlog, sinangag'),
(2,'en','Cornsilog','corned beef, fried egg, garlic fried rice'),
(2,'fr','Cornsilog','corned beef, œuf frit, riz frit à l'\'ail'),
(2,'tl','Cornsilog','corned beef, pritong itlog, sinangag'),
(2,'en','Calamari',''),
(2,'fr','Calamars',''),
(2,'tl','Calamari',''),
(2,'en','Shanghai (10 pcs.)',''),
(2,'fr','Shanghai (10 pièces)',''),
(2,'tl','Shanghai (10 piraso)',''),
(2,'en','Siomai',''),
(2,'fr','Siomai',''),
(2,'tl','Siomai',''),
(2,'en','Tofu Veggies',''),
(2,'fr','Légumes au Tofu',''),
(2,'tl','Tofu at Gulay',''),
(2,'en','Stirfry Veggies',''),
(2,'fr','Légumes Sautés',''),
(2,'tl','Stirfry na Gulay','');

INSERT INTO menu_prices (item_id, price) VALUES
(1, 74.99),
(2, 89.99),
(3, 15.99),
(4, 14.99),
(5, 14.99),
(6, 14.99),
(7, 14.99),
(8, 10.99),
(9, 8.50),
(10, 9.50),
(11, 11.99),
(12, 10.99);