-- Main Menu Items

INSERT INTO menu_items (category_id, code) VALUES
(4, 'menu.specials.extras.chicken.wings.title'),
(4, 'menu.specials.extras.baby.back.ribs.title'),
(4, 'menu.specials.extras.dinakdakan.title'),
(4, 'menu.specials.extras.sisig.title'),
(4, 'menu.specials.extras.lechon.kawali.title'),
(4, 'menu.specials.extras.dinuguan.title'),
(4, 'menu.specials.extras.beef.steak.title'),
(4, 'menu.specials.extras.bicol.express.title'),
(4, 'menu.specials.extras.fish.fillet.title'),
(4, 'menu.specials.extras.sweet.sour.fish.title'),
(4, 'menu.specials.extras.bucket.shrimp.title'),
(4, 'menu.specials.extras.dried.dangit.title'),
(4, 'menu.specials.extras.dried.pusit.title'),
(4, 'menu.specials.extras.pork.bbq.skewer.title'),
(4, 'menu.specials.extras.chicken.bbq.title'),
(4, 'menu.specials.extras.fried.chicken.title'),
(4, 'menu.specials.extras.steam.rice.title'),
(4, 'menu.specials.extras.pork.ribs.title'),
(4, 'menu.specials.extras.garlic.fried.rice.title'),
(4, 'menu.specials.extras.bangus.title'),
(4, 'menu.specials.extras.chorizo.title');


INSERT INTO menu_descriptions (item_id, lang_code, title, description) VALUES
(4,'en','Chicken Wings',''),
(4,'fr','Ailes de poulet',''),
(4,'tl','Chicken Wings',''),
(4,'en','Baby Back Ribs',''),
(4,'fr','Côtes levées de porc',''),
(4,'tl','Baby Back Ribs',''),
(4,'en','Dinakdakan','grilled pork head cheese, red onions, calamansi juice'),
(4,'fr','Dinakdakan','fromage de tête de porc grillé, oignons rouges, jus de calamansi'),
(4,'tl','Dinakdakan','inihaw na ulo ng baboy, pulang sibuyas, katas ng calamansi'),
(4,'en','Sisig','grilled pork jowl, pork belly, onions, chili peppers'),
(4,'fr','Sisig','joue de porc grillée, poitrine de porc, oignons, piments'),
(4,'tl','Sisig','inihaw na pisngi ng baboy, tiyan ng baboy, sibuyas, sili'),
(4,'en','Lechon Kawali','deep fried pork belly'),
(4,'fr','Lechon Kawali','poitrine de porc frite'),
(4,'tl','Lechon Kawali','pritong tiyan ng baboy'),
(4,'en','Dinuguan','pork offal stew, chili, vinegar'),
(4,'fr','Dinuguan','ragoût d'\'abats de porc, piment, vinaigre'),
(4,'tl','Dinuguan','nilagang lamang-loob ng baboy, sili, suka'),
(4,'en','Beef Steak',''),
(4,'fr','Bifteck',''),
(4,'tl','Beef Steak',''),
(4,'en','Bicol Express','pork cubes, coconut milk, chili peppers, allium stew'),
(4,'fr','Bicol Express','cubes de porc, lait de coco, piments, ragoût d'\'ailiacées'),
(4,'tl','Bicol Express','cube ng baboy, gata ng niyog, sili, nilagang allium'),
(4,'en','Fish Fillet',''),
(4,'fr','Filet de poisson',''),
(4,'tl','Fish Fillet',''),
(4,'en','Sweet and Sour Fish',''),
(4,'fr','Poisson aigre-doux',''),
(4,'tl','Sweet and Sour Fish',''),
(4,'en','Bucket Shrimp',''),
(4,'fr','Seau de crevettes',''),
(4,'tl','Bucket ng Hipon',''),
(4,'en','Dried Danggit','Dried Fish'),
(4,'fr','Danggit Séché','Poisson séché'),
(4,'tl','Pinatuyong Danggit','Pinatuyong Isda'),
(4,'en','Dried Pusit','Dried Squid'),
(4,'fr','Pusit Séché','Calmar séché'),
(4,'tl','Pinatuyong Pusit','Mga Karagdagang'),
(4,'en','Pork BBQ Skewer',''),
(4,'fr','Brochette de porc BBQ',''),
(4,'tl','Pork BBQ Skewer',''),
(4,'en','Chicken BBQ',''),
(4,'fr','Poulet BBQ',''),
(4,'tl','Chicken BBQ',''),
(4,'en','Fried Chicken (1 pc.)','Less than 10: $3.00 each, More than 10: $2.50 each'),
(4,'fr','Poulet Frit (1 pièce)','Moins de 10: 3,00 $ chacun, Plus de 10: 2,50 $ chacun'),
(4,'tl','Fried Chicken (1 piraso)','Mas mababa sa 10: $3.00 bawat isa, Higit sa 10: $2.50 bawat isa'),
(4,'en','Steam Rice',''),
(4,'fr','Riz Vapeur',''),
(4,'tl','Kanin',''),
(4,'en','Pork Ribs',''),
(4,'fr','Côtes de Porc',''),
(4,'tl','Pork Ribs',''),
(4,'en','Garlic Fried Rice',''),
(4,'fr','Riz Frit à l'\'Ail',''),
(4,'tl','Sinangag',''),
(4,'en','Bangus (1 whole pc.)','fried whole fish'),
(4,'fr','Bangus (1 pièce entière)','poisson entier frit'),
(4,'tl','Bangus (1 buong piraso)','pritong buong isda'),
(4,'en','Chorizo (4 pcs.)','Filipino style spicy sausage'),
(4,'fr','Chorizo (4 pièces)','Saucisse épicée de style philippin'),
(4,'tl','Chorizo (4 na piraso)','Filipino style na maanghang na longganisa');



INSERT INTO menu_prices (item_id, price) VALUES
(1, 8.99),
(2, 16.99),
(3, 16.99),
(4, 16.99),
(5, 16.99),
(6, 17.99),
(7, 17.99),
(8, 16.99),
(9, 10.99),
(10, 16.99),
(11, 21.99),
(12, 14.99),
(13, 14.99),
(14, 3.99),
(15, 7.99),
(16, ),
(17, 2.50),
(18, 13.99),
(19, 7.50),
(20, 6.99),
(21, 6.99);